<?php
class DataObjectTemplate extends dclaysmith\Generator\Template {

	public $table;

	public function generate() {

		$aOutput[] = <<<EOF

<?php
/**
 * abstract class Account_Base
 *
 * This class defines an OO representation of the {$this->table->name} table
 *
 * NOTE: This file is autogenerated from the {$this->table->name} using
 * the CG2K6.
 *
 * IMPORTANT: This file should NEVER BE CHANGED BY HAND. NEVER! Any changes
 * that need to be made should be made to the template file and replicated for
 * all tables.
 *
 * USAGE: This is an abstract class and thus it must be inherited. Create a
 * or modify business object to use this file. Business Objects are stored in
 * the "/bo" directory.
 *
 * PHP version 5
 *
 * @category   Data Object
 * @author     D CLAY SMITH
 * @copyright  2007 D Clay Smith
 */
if (!defined('MEMCACHE_ENABLED')) define('MEMCACHE_ENABLED', 'false');

abstract class Account_Base extends CDataObject {

	/**
	 * Constructor
	 */
	function __construct() {
	}

	/**
	 * Variables
	 */
EOF;

		foreach ($this->table->columns() as $column) {
			$aOutput[] = "protected $_".$column->name.";";
		}

		$aOutput[] = <<<EOF
}
?>
EOF;

		echo implode("\n",$aOutput);
		die;

		return implode("\n",$aOutput);
	}

}
?>